pipeline {
    agent any

    stages {
        stage('build') {
            agent {
                docker {
                    image 'henryw7/terachem_compilation_enviroment:latest'
                    alwaysPull true
                }
            }
            steps {
                echo 'Building TCPB-cpp...'
                sh './configure gnu'
                sh 'make install'
                echo 'Done building TCPB-cpp'
            }
        }
    }
}
