pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                echo 'Building TCPB-cpp...'
                sh './configure gnu'
                sh 'make install'
                echo 'Done building TCPB-cpp'
            }
        }
    }
}
